import "@/styles/utilities.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/hooks/useDarkLightTheme";
import ReduxProvider from "@/providers/ReduxProvider";

const quicksand = Quicksand({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Al Riwaa App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased`}>
        <ReduxProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
